name: run-sample


inputs:
  language:
    required: true
    description: The programming language of the code sample


runs:
  using: composite
  steps:
    - name: Build and run
      run: |
        cd samples/${{ inputs.language }}

        docker build -t weather-app .
        docker run --rm weather-app tokyo
      shell: bash
