version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /image/bare
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /image/full
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /image/edge
    schedule:
      interval: daily
