name: build-and-push


inputs:
  path:
    required: true
    description: The directory path of the Dockerfile (context location)

  image-name:
    required: true
    description: The Docker image name (user/repo:tag)

  tag-suffix:
    required: true
    description: The Docker image tag suffix (bare, full, edge etc)

  dockerhub-token:
    required: true
    description: Authentication token for Docker Hub

  push-latest:
    required: false
    default: 'no'
    description: Whether the Docker image should also be pushed with the latest tag or not


runs:
  using: composite
  steps:
    - name: Lint Dockerfile
      run: docker run --rm -i hadolint/hadolint < ${{ inputs.path }}/Dockerfile
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: caian
        password: ${{ inputs.dockerhub-token }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: |
          build-image-${{ inputs.tag-suffix }}-buildx-${{ github.sha }}
          build-image-${{ inputs.tag-suffix }}-buildx-
        restore-keys: |
          build-image-${{ inputs.tag-suffix }}-buildx-

    - name: Build and push "${{ inputs.tag-suffix }}" image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ inputs.image-name }}-${{ inputs.tag-suffix }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Push "${{ inputs.tag-suffix }}" image with "latest" tag
      if: inputs.push-latest == 'yes'
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ inputs.image-name }}-${{ inputs.tag-suffix }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
