name: build-bare-image


on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  build-bare-image:
    runs-on: ubuntu-latest
    env:
      tag-suffix: bare

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: caian/sample-devcontainer
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=false

      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          path: images/${{ env.tag-suffix }}
          image-name: ${{ steps.meta.outputs.tags }}-${{ env.tag-suffix }}
          tag-suffix: ${{ env.tag-suffix }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
