name: build-full-image


on:
  repository_dispatch:
    types: [build-full-image]


jobs:
  build-full-image:
    runs-on: ubuntu-latest
    env:
      tag-suffix: full

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          path: images/${{ env.tag-suffix }}
          image-name: ${{ github.event.client_payload.tag }}
          tag-suffix: ${{ env.tag-suffix }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trigger "edge" image build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          event-type: build-edge-image
          client-payload: '{"tag": "${{ steps.meta.outputs.tags }}"}'
