name: build-bare-image


on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  build-bare-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < images/bare/Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: caian
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retrieve metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: caian/sample-devcontainer
          tags: type=semver,pattern={{version}}-bare

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: build-bare-image-buildx-${{ github.sha }}
          restore-keys: |
            build-bare-image-buildx-

      - name: Build and push "bare" (base) image
        uses: docker/build-push-action@v2
        with:
          context: images/bare
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
