name: build-bare-image


on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  build-bare-image:
    runs-on: ubuntu-latest
    env:
      image-name: caian/sample-devcontainer
      tag-suffix: bare

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.image-name }}
          tags: type=semver,pattern={{version}}
          flavor: latest=false

      - name: Build and push "${{ env.tag-suffix }}" image
        uses: ./.github/actions/build-and-push
        with:
          path:            "images/${{ env.tag-suffix }}"
          tag-suffix:      "${{ env.tag-suffix }}"
          tagged-name:     "${{ steps.meta.outputs.tags }}"
          dockerhub-token: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Trigger "full" image build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          event-type: build-full-image
          client-payload: >
            {
              "tagged_name": "${{ steps.meta.outputs.tags }}"
            }
