name: build-full-image


on:
  repository_dispatch:
    types: [build-full-image]


jobs:
  build-full-image:
    runs-on: ubuntu-latest
    env:
      image-name: caian/sample-devcontainer
      tag-suffix: full

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push "${{ env.tag-suffix }}" image
        uses: ./.github/actions/build-and-push
        with:
          path:            "images/${{ env.tag-suffix }}"
          tag-suffix:      "${{ env.tag-suffix }}"
          tagged-name:     "${{ github.event.client_payload.tagged_name }}"
          dockerhub-token: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Trigger "edge" image build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          event-type: build-edge-image
          client-payload: >
            {
              "tagged_name": "${{ github.event.client_payload.tagged_name }}"
            }
