name: build-edge-image


on:
  push:
    branches: [edge]

  pull_request:
    branches: [edge]

  schedule:
    - cron: '0 3,11,19 * * *'

  repository_dispatch:
    types: [build-edge-image]

  workflow_dispatch:


jobs:
  build-edge-image:
    runs-on: ubuntu-latest
    env:
      image-name: caian/sample-devcontainer
      tag-suffix: edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push "${{ env.tag-suffix }}" image
        uses: ./.github/actions/build-and-push
        with:
          path:            "images/${{ env.tag-suffix }}"
          tag-suffix:      "${{ env.tag-suffix }}"
          image-name:      "${{ env.image-name }}"
          dockerhub-token: "${{ secrets.DOCKERHUB_TOKEN }}"
          push-latest:     "yes"

      - name: Trigger the code sample tests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          event-type: run-sample
