name: build-edge-image


on:
  push:
    branches: [edge]

  pull_request:
    branches: [edge]

  schedule:
    - cron: '0 3,11,19 * * *'

  repository_dispatch:
    types: [build-edge-image]

  workflow_dispatch:


jobs:
  build-edge-image:
    runs-on: ubuntu-latest
    env:
      tag-suffix: edge

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          path: images/${{ env.tag-suffix }}
          image-name: caian/sample-devcontainer
          tag-suffix: ${{ env.tag-suffix }}
          push-latest: 'yes'
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
